#switch("cc", "clang")
#switch("passL", "-lclang")
switch("threads", "on")
switch("mm", "orc")
switch("multimethods", "on")
switch("passC", "-flto")
switch("passL", "-flto")
switch("path", "lib")
# switch("define", "release")
# switch("define", "danger")
# switch("opt", "speed")
# switch("app", "gui")
# switch("maxLoopIterationsVM", "1000000000")

#switch("forceBuild", "on")